# Generated by Django 3.0.7 on 2020-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SumItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_items', models.TextField()),
                ('items_cost', models.TextField()),
                ('items_weight', models.TextField()),
                ('date_created', models.DateField(null=True)),
            ],
        ),
    ]
