# Generated by Django 3.0.7 on 2020-07-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumitems',
            name='items_price',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sumitems',
            name='total_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sumitems',
            name='user_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sumitems',
            name='items_cost',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sumitems',
            name='items_weight',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sumitems',
            name='selected_items',
            field=models.TextField(null=True),
        ),
    ]
