# Generated by Django 3.0.7 on 2020-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSumItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('pnumber', models.IntegerField()),
                ('selected_items', models.TextField(null=True)),
                ('items_cost', models.TextField(default=0, null=True)),
                ('items_weight', models.TextField(default=0, null=True)),
                ('items_price', models.TextField(default=0, null=True)),
                ('total_cost', models.FloatField(default=0, null=True)),
                ('date_created', models.DateField(null=True)),
            ],
        ),
    ]
