# Generated by Django 3.0.7 on 2020-07-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psumitems',
            name='pnumber',
            field=models.IntegerField(null=True),
        ),
    ]
