# Generated by Django 3.0.7 on 2020-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0002_auto_20200723_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='psumitems',
            name='status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
