# Generated by Django 3.0.7 on 2020-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0004_auto_20200807_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psumitems',
            name='pnumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
