# Generated by Django 3.0.7 on 2020-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_pdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDetails',
        ),
    ]
